remote_theme: pmarsceill/just-the-docs


title: "BM1: Advanced Natural Language Processing"

email: david.schlangen@uni-potsdam.de

description: >- # this means to ignore newlines until "baseurl:"
  Course website for BM1: Advanced Natural Language Processing

search_enabled: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

aux_links:
  "All Classes":
  - "//github.com/compling-potsdam"

permalink: pretty

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

